apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  annotations:
{{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value }}
{{- end }}
  labels:
{{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
{{- range $key, $value := .Values.deployment.labels }}
      {{ $key }}: {{ $value }}
{{- end }}
  template:
    metadata:
      labels:
{{- range $key, $value := .Values.deployment.labels }}
        {{ $key }}: {{ $value }}
{{- end }}
      annotations:
{{- range $key, $value := .Values.deployment.podAnnotations }}
        {{ $key }}: {{ $value }}
{{- end }}
    spec:
      tolerations:
{{- range $i, $toleration := .Values.deployment.tolerations }}
      - key: {{ $toleration.key }}
        operator: {{ $toleration.operator }}
        value: {{ $toleration.value }}
        effect: {{ $toleration.effect }}
{{- end }}
      containers:
      - name: flatpress
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: 8080
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: fp-content
          mountPath: /var/www/html/fp-content
        {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: fp-content
        persistentVolumeClaim:
          claimName: fp-content-pvc
      {{- end }}
