{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flatpress-ingress
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: flatpress-tls-secret
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: {{ .Values.service.name }}
            port: 
              number: 8080
{{- end }}
