---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: flatpress
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
