ingress:
  enabled: true
  hostname: flatpress.example.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "flatpress.example.com"

deployment:
  name: flatpress
  replicas: 3
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: flatpress
  podAnnotations:
    prometheus.io/port: "8080"
  tolerations: []
  image: ghcr.io/inputobject2/flatpress-docker:latest
